spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cacheframework?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 969zmyZMY
  devtools:
    restart:
      enabled: true
      additional-paths: src/main
      exclude: static/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.entity
  configuration:
    mapUnderscoreToCamelCase: true
